#!/bin/sh
# export GEM_HOME="{{pkg.path}}/ruby/2.4.0"
# export GEM_PATH="$(hab pkg path core/ruby)/lib/ruby/gems/2.4.0:$(hab pkg path core/bundler):$GEM_HOME"
# export APPBUNDLER_ALLOW_RVM=true
exec 2>&1

export SSL_CERT_FILE="{{pkgPathFor "core/cacerts"}}/ssl/cert.pem"

exec chef-solo --fork -c {{pkg.svc_config_path}}/client.rb -i {{cfg.interval}} -s {{cfg.splay}} -l {{cfg.log_level}}
